/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DotProduct */

#ifndef _Included_DotProduct
#define _Included_DotProduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DotProduct
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_DotProduct_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     DotProduct
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_DotProduct_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     DotProduct
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DotProduct_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
